### PR TITLE
make a new component to upload image and file

### PR DESCRIPTION
**Pull request by SantoshChapagai**
Ticket: UP-143
Users can directly upload images or files. The uploaded file or image loads on the input and gives the output based on the selection.
Screenshot 2024-02-06 at 15 26 14

### CODE REVIEW

**Comment by amitkalwar** [comment]
Please place the icons on the top not on side 
- get some inspiration from Google Translator buttons and icons

**Comment by unellma** [comment]
[UnelmaSupport](https://unelmasupport.com)

# Hello!

Thanks for getting in touch! This is an automatic email just to let you know that we've received your request and your ticket reference is #559.

One of our support agents will get back to you shortly. Please do not submit multiple tickets for the same request, as this will not result in a faster response time.

View Help Center: https://unelmasupport.com/hc

Regards,
UnelmaSupport

If you’re having trouble clicking the "View Help Center" button, copy and paste the URL below into your web browser: [https://unelmasupport.com/hc](https://unelmasupport.com/hc)

© 2024 UnelmaSupport. All rights reserved.

**Review by unellma — COMMENTED** [review]
- You will need to rebase this branch from main/master
- Looks like it is showing old css in preview
- Align those File and Document icons towards left in Input section

**Comment by unellma** [comment]
@SantoshChapagai  

Add a tooltip, when user puts mouse of those icons
- Upload an image to translate your code
- Upload a file to translate your code

**Review by amitkalwar — APPROVED** [review]
txt and image is working

**Comment by unellma** [comment]
[UnelmaSupport](https://unelmasupport.com)

# Hello!

Thanks for getting in touch! This is an automatic email just to let you know that we've received your request and your ticket reference is #590.

One of our support agents will get back to you shortly. Please do not submit multiple tickets for the same request, as this will not result in a faster response time.

View Help Center: https://unelmasupport.com/hc

Regards,
UnelmaSupport

If you’re having trouble clicking the "View Help Center" button, copy and paste the URL below into your web browser: [https://unelmasupport.com/hc](https://unelmasupport.com/hc)

© 2024 UnelmaSupport. All rights reserved.

**Review by unellma — APPROVED** [review]

**Pull request merged**
